SELECT * from Person WHERE idPerson=:idPerson;
SELECT * from Person WHERE name=:name;
SELECT * from Client WHERE idPerson=:idPerson;
SELECT * from Client WHERE name=:name;
SELECT * from Supplier WHERE idPerson=:idPerson;
SELECT * from Supplier WHERE name=:name;
SELECT * from Userino WHERE idPerson=:idPerson;
SELECT * from Userino WHERE userName=:userName;
SELECT * from Manager;
SELECT * from PoSOperator WHERE idPerson=:idPerson;
SELECT * from PoSOperator WHERE userName=:userName;
SELECT * from ShopKeeper WHERE idPerson=:idPerson;
SELECT * from ShopKeeper WHERE userName=:userName;
SELECT * from Report WHERE idReport=:idReport;
SELECT * from Building WHERE idBuilding=:idBuilding;
SELECT * from Storage WHERE idBuilding=:idBuilding;
SELECT * from PointOfSale WHERE idBuilding=:idBuilding;
SELECT * from Product WHERE name=:name;
SELECT * from Product WHERE price=:price;
SELECT * from Product WHERE expirationDate=:expirationDate;
SELECT * from Product WHERE idProduct=:idProduct;
SELECT * from Transaction;
SELECT * from SupplierCompany;
SELECT * from Orderino WHERE orderDate=:orderDate;
SELECT * from Orderino WHERE paymentDate=:paymentDate;
SELECT * from Orderino WHERE deliveryDate=:deliveryDate;
SELECT * from ProductOrder;
SELECT * from ProductBuilding;
SELECT * from ShopkeeperPointOfSale;
SELECT * from Quantity;

SELECT name,ban,fin,telephone from Client WHERE name=:name;
SELECT name,ban,fin,telephone from Supplier WHERE name=:name;
SELECT userName, photograph, salary from Userino WHERE userName=:userName;
SELECT userName, photograph, salary from Userino WHERE photograph=:photograph;
SELECT userName, photograph, salary from Userino WHERE salary=:salary;
SELECT userName, photograph, salary from PoSOperator WHERE userName=:userName;
SELECT userName, photograph, salary from PoSOperator WHERE photograph=:photograph;
SELECT userName, photograph, salary from PoSOperator WHERE salary=:salary;
SELECT userName, photograph, salary from ShopKeeper WHERE userName=:userName;
SELECT userName, photograph, salary from ShopKeeper WHERE photograph=:photograph;
SELECT userName, photograph, salary from ShopKeeper WHERE salary=:salary;
SELECT name, content from Report WHERE name=:name;
SELECT zipCode,address from Building WHERE address=:address;
SELECT zipCode,address from Storage WHERE address=:address;
SELECT zipCode,address from PointOfSale WHERE address=:address;
SELECT name, price from Product WHERE name=:name;
SELECT name, price from Product WHERE price=:price;
SELECT expirationDate,description from Product WHERE expirationDate=:expirationDate;
SELECT photograph,name,category,idProduct from Product WHERE idProduct=:idProduct;
SELECT orderDate,paymentDate,deliveryDate from Orderino WHERE orderDate=:orderDate;
SELECT orderDate,paymentDate,deliveryDate from Orderino WHERE paymentDate=:paymentDate;
SELECT orderDate,paymentDate,deliveryDate from Orderino WHERE deliveryDate=:deliveryDate;