SELECT * from Person;
SELECT * from Client;
SELECT * from Supplier;
SELECT * from Userino;
SELECT * from Manager;
SELECT * from PoSOperator;
SELECT * from ShopKeeper;
SELECT * from Report;
SELECT * from Building;
SELECT * from Storage;
SELECT * from PointOfSale;
SELECT * from Product;
SELECT * from Transaction;
SELECT * from SupplierCompany;
SELECT * from Orderino;
SELECT * from ProductOrder;
SELECT * from ProductBuilding;
SELECT * from ShopkeeperPointOfSale;
SELECT * from Quantity;

SELECT name,ban,fin,telephone from Client;
SELECT name,ban,fin,telephone from Supplier;
SELECT userName, photograph, salary from Userino;
SELECT userName, photograph, salary from PoSOperator;
SELECT userName, photograph, salary from ShopKeeper;
SELECT name, content from Report;
SELECT zipCode,address from Building;
SELECT zipCode,address from Storage;
SELECT zipCode,address from PointOfSale;
SELECT name, price from Product;
SELECT expirationDate,description from Product;
SELECT photograph,name,category,idProduct from Product;
SELECT orderDate,paymentDate,deliveryDate from Orderino;